### PR TITLE
Challenge Submission

### PR DESCRIPTION
**Pull request by c0dect**
- Added distributor permissions in distributor.txt
        - Added input cases in input.txt
        - Added source code in main.go

The code can be run using the command

`go run main.go distributors.txt input.txt output.txt`

### CODE REVIEW

**Comment by c0dect** [comment]
I don't get the sample case given in the README.md file.
`DISTRIBUTOR1` is asked to Exclude `KARNATAKA-INDIA`

`DISTRIBUTOR3` is a sub-distributor of `DISTRIBUTOR2` which is a sub-distributor of `DISTRIBUTOR1`. Then how is `DISTRIBUTOR3` allowed to distribute in `HUBLI-KARNATAKA-INDIA`, since `DISTRIBUTOR1` itself doesn't have that right.

Am I missing something here?

**Comment by sivachandran** [comment]
@c0dect DISTRIBUTOR3 is mentioned as negative case.

**Comment by c0dect** [comment]
Aah. Sorry, missed that line. Thanks. 
@sivachandran I request you to kindly evaluate my submission.

**Comment by sivachandran** [comment]
@c0dect Thanks for the submission. Can you make the program interactive like accepting the input and printing the result immediately? It is difficult to touch multiple files to give input and verify the result.

**Comment by c0dect** [comment]
@sivachandran Sure, I can do that. I thought the current approach would be more convenient for you as you would have to merely enter all your test cases, sequentially in the "input.txt" file and check all the answers from the "output.txt" file. 

However, I shall update the solution according to the required changes.

**Comment by c0dect** [comment]
@sivachandran I have updated the code now. The current code can be run using the command:

`go run main.go distributors.txt  DISTRIBUTOR1 CHICAGO-ILLINOIS-UNITEDSTATES`

"distributors.txt" is the rules file. The next two arguments are the input distributor and the location.

Kindly have a look and let me know.

**Comment by c0dect** [comment]
@sudhirj @sivachandran Is there any update on the status of the challenge?

**Comment by sivachandran** [comment]
@c0dect The program fails for the following case

```
$ cat distributors.txt
...
Permissions: DISTRIBUTOR10
INCLUDE: TN-IN

$ ./challenge2016 distributors.txt DISTRIBUTOR10 CENAI-TN-IN
NO
```

Expected output is *YES*.

**Comment by sivachandran** [comment]
@c0dect I've gone through the implementation and it looks like the program doesn't inherit the rules properly, especially when the distribution region is narrowed by the lower level distributors. For example, the expected output of the program is **NO** whereas it outputs **YES**.

```
$ cat distributors.txt 
Permissions: DISTRIBUTOR1
INCLUDE: INDIA
INCLUDE: UNITEDSTATES
EXCLUDE: KARNATAKA-INDIA
EXCLUDE: CHENNAI-TAMILNADU-INDIA

Permissions: DISTRIBUTOR2 < DISTRIBUTOR1
INCLUDE: INDIA
EXCLUDE: TAMILNADU-INDIA

Permissions: DISTRIBUTOR3 < DISTRIBUTOR2 < DISTRIBUTOR1
INCLUDE: HUBLI-KARNATAKA-INDIA
...

$ ./challenge2016 distributors.txt DISTRIBUTOR2 SANFRANCISCO-CALIFORNIA-UNITEDSTATES
YES
```

**Comment by c0dect** [comment]
@sivachandran Sorry for making erroneous submissions. I have fixed it now.

**Pull request closed without merging**
