### PR TITLE
Gophercon2016 Challenge

### PR DESCRIPTION
**Pull request by haridas**
To run the code run bellow command inside the project folder.

` $ go test`

### CODE REVIEW

**Comment by sivachandran** [comment]
Thanks for the submission. Will check it out and let you know.

**Comment by sivachandran** [comment]
Getting panic if only exclusions are specified for a distributor.

**Comment by haridas** [comment]
Ohh, will check this case and update it..

**Comment by haridas** [comment]
Looks like, I'm able to run the script with Distributor with only exclusions, provided this Distributor has been inheriting some inclusions from parent Distributor. I pushed one more commit with more test cases that checks these scenarios.

One probable thing would be wrong CSV format would have thrown the panic. Hope that addresses the problem.

**Comment by haridas** [comment]
@sivachandran Did you get any chance to check this updated test case ?

**Comment by sivachandran** [comment]
@haridas With the distributor rule `D9,,TN-IN` the distribution `D9,VRKLA-KL-IN` is allowed but the program outputs as "OFF".

**Comment by haridas** [comment]
"List of only exclusions" is not addressed here, as I saw a comment on another submission. Will fix this up and update.

**Comment by haridas** [comment]
@sivachandran Addressed the global exclusion scenarios, updated the PR. Please check it out.

**Comment by sivachandran** [comment]
@haridas The distribution `D2,MDURI-TN-IN` is allowed as per the distributor rules specified in dist_permissions.csv but the program says OFF.

**Comment by haridas** [comment]
@sivachandran as D2 is child distributor of D1, and also it has complete exclusion in TN-IN. So as per this, D2 don't have permission to distribute entire TN-IN and KA-IN. I picked the default example specified in the README.md file for D1 and D2, It also specifying the same thing. Please let me know if I miss anything here.

**Comment by sivachandran** [comment]
@haridas You are correct. I confused D2 with D1, my bad. Will check other cases and update.

**Comment by sivachandran** [comment]
@haridas The program passes most of the cases but it seems to be failing for the following case

```
$ cat dist_permission.csv
...
D12,,TN-IN
...
$ ./challenge2016 

1. Check Distributer Permission: 
2. Quit.
Enter Your choice: 1
Your Choice: 1
Enter the Input eg: D1, CITY-PROVINCE-COUNTRY format: D12, SFRIC-CA-US
 Distributer: D12, Location SFRIC-CA-US - Has permission ?: OFF
```

Also if I try to specify only inclusion like `D13,TN-IN,` then the program crashes.

**Comment by haridas** [comment]
@sivachandran  

`D13, TN-IN`, working fine for me, please check the screenshot on this bellow link, https://github.com/haridas/challenge2016/blob/master/d13-out.png

Regarding the only exclusion scenario, I'm not including all countries into the global inclusion for that distributor, instead distributor has access till in the particular country only.

Currently If we say like `D1,,TN-IN` means, D1 is being excluded in Tamilnadu, but included all parts of India. If you are expecting the behavior like, `D1` is excluded in Tamilnadu but included all over the world, then please let me know I will update it accordingly.

**Comment by sivachandran** [comment]
Yes @haridas. We are expecting to include the entire world except what is mentioned in the exclude list.

I will check the inclusion only case again.

**Comment by haridas** [comment]
Ok @sivachandran Will update it accordingly.

**Comment by haridas** [comment]
@sivachandran Updated the code, now the global inclusion in place if we give only the exclusion for a distributor. Please check it out.

**Comment by sivachandran** [comment]
@haridas Your last change does exact match for the exclusion list. But it is perfectly valid to exclude country or state level. I did a quick test and the program fails for the following case.

```
$ cat dist_permission.csv
...
D12,,TN-IN
...

$ ./challenge2016 

1. Check Distributer Permission: 
2. Quit.
Enter Your choice: 1
Your Choice: 1
Enter the Input eg: D1, CITY-PROVINCE-COUNTRY format: D12, CENAI-TN-IN
 Distributer: D12, Location CENAI-TN-IN - Has permission ?: ON
```

**Comment by haridas** [comment]
@sivachandran Yes, you are correct. My bad, I missed to add that in my test case. We don't need exact match and existing sub-location identification method can be reused here also. I will update it accordingly and update you.

**Comment by haridas** [comment]
@sivachandran pushed the fix, and update the testcase, please verify it.

**Comment by haridas** [comment]
@sivachandran Any update on this ?

**Comment by sivachandran** [comment]
@haridas We will send a mail soon.

**Pull request closed without merging**
