### PR TITLE
 Solution by Nth Movie Buff!

### PR DESCRIPTION
**Pull request by nthmoviebuff**

### CODE REVIEW

**Comment by nthmoviebuff** [comment]
@sivachandran @sudhirj ^

**Comment by nthmoviebuff** [comment]
@sivachandran @sudhirj Are you guys considering this Ruby solution?

**Comment by sudhirj** [comment]
Thanks for submitting :+1: Will take a look and keep you informed. And yes, we will consider Ruby.

**Comment by nthmoviebuff** [comment]
@sivachandran @sudhirj Did you guys find time to look at this Ruby solution?

**Comment by sudhirj** [comment]
@nthmoviebuff Not yet - we're waiting for a few more submissions to come in before we start judging.

**Comment by sudhirj** [comment]
I can confirm that your code works in general, though, but what do you expect will happen in this case?

```
Permissions for DISTRIBUTOR7
EXCLUDE: KARNATAKA-INDIA
```

```
DISTRIBUTOR7, BANGALORE-KARNATAKA-INDIA, false
DISTRIBUTOR7, TAMIL NADU-INDIA, true
```

**Comment by nthmoviebuff** [comment]
@sudhirj Thanks for taking a look at this Ruby solution.

```DISTRIBUTOR7, BANGALORE-KARNATAKA-INDIA, false``` - It will pass as Distributor7 has been excluded explicitly.

```DISTRIBUTOR7, TAMIL NADU-INDIA, true`` - this will fail as Distributor 7 has no parent distributor and hasn't included any region - expected result should be "false".

**Comment by sudhirj** [comment]
Let me double check if we're judging on this, but a list of only exclusions implies a global inclusion - it would be meaningless and invalid otherwise.

**Comment by sivachandran** [comment]
@nthmoviebuff Can you share your email address?

**Comment by nthmoviebuff** [comment]
@sivachandran ```nthmoviebuff``` is my gmail id.

**Pull request closed without merging**
