### PR TITLE
Solution created for the challenge2016

### PR DESCRIPTION
**Pull request by arjunajithtp**

### CODE REVIEW

**Comment by sivachandran** [comment]
@arjunajithtp I tried running your solution. It doesn't allow me to create distributor at the country or province level. It is forcing me to select all the cities too. Am I missing something? Moreover I don't know how to check/test distribution rights after creating a distributor.

**Comment by arjunajithtp** [comment]
@sivachandran First of all, let me apologise for the delay I caused to update the code. I had updated the code with the facility to create distributor at country or province level. I also added a view page for listing the distributor cities. This page also have a search option. Thank you.

**Comment by sivachandran** [comment]
@arjunajithtp If my understanding is correct, every time we save a distributor we store all allowed cities of the distributor regardless at which level we are restricting(i.e. country, province). The problem I see here is what if a city movies from one province to another(e.g. Hyderabad moving under Telangana province). How to handle province bifurcating or merging scenarios(e.g. Andra Pradesh becoming Andra Pradesh and Telangana)?

**Comment by arjunajithtp** [comment]
@sivachandran Sorry I haven't thought about that problem. I think I know how to solve such a situation. I will store the data according to the 'Saving Level' (For eg. only country code will be added if it is saved at the country level). I will update the code ASAP.

**Comment by arjunajithtp** [comment]
@sivachandran The issue is solved by storing the codes at the corresponding level. I also found and solved issues with multiple countries, provinces or cities have same name. Also added save button hide until name and at least on checkbox is selected, which will solve another newly found issue of blank data file saving. Added country name with provinces and both country and province name with cities, which I hope will reduce the confusion for the user. Added search text box with the listing of distributors.

**Pull request closed without merging**
