### PR TITLE
solution of challenge 2016

### PR DESCRIPTION
**Pull request by souvikhaldar**
Started working on the solution.

### CODE REVIEW

**Comment by souvikhaldar** [comment]
It's not the final commit but the solution is almost done, it just needs little fix. My final commit will be at 3 pm IST and I'll revert to you then.

**Comment by souvikhaldar** [comment]
Checking for regions is working-
image

image

**Comment by souvikhaldar** [comment]
image

image

**Comment by souvikhaldar** [comment]
It is now ready for review.

**Comment by sudarshan-reddy** [comment]
@souvikhaldar can you add the unit tests as well please?

**Comment by souvikhaldar** [comment]
@sudarshan-reddy  Unit tests are now added.

**Comment by souvikhaldar** [comment]
Final working example:-
Checking permission assignment
image


Checking permission
image

**Pull request closed without merging**
