### PR TITLE
Challenge2016 - gophercon

### PR DESCRIPTION
**Pull request by govindarajan**
- Script to find out the authorization of a distributor with the given set of rules.
- Please refer howto.txt for more details on how to run.

### CODE REVIEW

**Comment by sudhirj** [comment]
Thanks for the submission :+1: Will check it out and let you know.

**Comment by sivachandran** [comment]
Doesn't work for the following cases

**Case 1:**
expected output is YES but outputs NO
```
$ cat distributors.rule
...
Permissions: DISTRIBUTOR5
EXCLUDE: US
...

$ go run distributors.go distributors.rule DISTRIBUTOR5 CENAI-TN-IN
NO
```

**Case 2:**
expected output is YES but outputs NO
```
$ cat distributors.rule
...
Permissions: DISTRIBUTOR6
INCLUDE: IN
INCLUDE: US

Permissions: DISTRIBUTOR7 < DISTRIBUTOR6
EXCLUDE: TN-IN
...

$ go run distributors.go distributors.rule DISTRIBUTOR7 FILMR-CA-US
NO
```

**Comment by govindarajan** [comment]
Hi, I thought Whenever there is INCLUDE location, we have to take that. Not all by default. It was my mistake. I assumed and wrote it. I should have asked this in the first place.

**Comment by govindarajan** [comment]
If above is the case, the following diff will give you the expected result.

diff --git a/distributors.go b/distributors.go
index 198be2d..8c21466 100644
--- a/distributors.go
+++ b/distributors.go
@@ -110,15 +110,15 @@ func isDistributorAllowed(name string, country string, state string, city string
                        }
                }
 
-               innerLoopInc := false
-               for _, ic := range dis.Includes {
-                       ci, s, co := getSplittedLocation(ic)
-                       if isSubset(ci, s, co, city, state, country) {
-                               innerLoopInc = true
-                               break
-                       }
-               }
-               included = included && innerLoopInc
+               // innerLoopInc := false
+               // for _, ic := range dis.Includes {
+               //      ci, s, co := getSplittedLocation(ic)
+               //      if isSubset(ci, s, co, city, state, country) {
+               //              innerLoopInc = true
+               //              break
+               //      }
+               // }
+               // included = included && innerLoopInc
 
                if dis.ParentDistributor == nil {
                        break

**Comment by sivachandran** [comment]
@govindarajan Your understanding about the distributor rule is correct. Can you merge your latest change with PR?

**Comment by govindarajan** [comment]
@sivachandran - committed and code. Please check it out .

**Comment by sivachandran** [comment]
@govindarajan For the following rules the program says `KNDUR-AP-IN` is a valid distribution for `DISTRIBUTOR3` whereas it is not.

```
$ cat distributors.rule
Permissions: DISTRIBUTOR1
INCLUDE: IN
INCLUDE: US
EXCLUDE: KA-IN
EXCLUDE: CENAI-TN-IN

Permissions: DISTRIBUTOR2 < DISTRIBUTOR1
EXCLUDE: DNIGU-TN-IN

Permissions: DISTRIBUTOR3 < DISTRIBUTOR1
INCLUDE: KOTAL-AP-IN

./challenge2016 distributors.rule DISTRIBUTOR3 KNDUR-AP-IN
YES
```

**Pull request closed without merging**
